services:
  site-2:
    command:
      - ${PYTHON_EXECUTABLE}
      - -u
      - -m
      - nvflare.private.fed.app.client.client_train
      - -m
      - ${WORKSPACE}
      - -s
      - fed_client.json
      - --set
      - secure_train=true
      - uid=site-2
      - org=nvidia
      - config_folder=config
    container_name: site-2
    image: ${IMAGE_NAME}
    volumes:
      - ../site-2:${WORKSPACE}
      - ../admin-site-2@nvidia.com:${WORKSPACE}/admin-site-2@nvidia.com
      - ../data2.csv:/tmp/nvflare/df_stats/data/site-2/data.csv
volumes:
  nvflare_svc_persist: null
