services:
  fed-server:
    command:
      - ${PYTHON_EXECUTABLE}
      - -u
      - -m
      - nvflare.private.fed.app.server.server_train
      - -m
      - ${WORKSPACE}
      - -s
      - fed_server.json
      - --set
      - secure_train=true
      - config_folder=config
      - org=nvidia
    container_name: fed-server
    image: ${IMAGE_NAME}
    ports:
      - 8002:8002
      - 8003:8003
    volumes:
      - ./fed-server:${WORKSPACE}
      - ./admin-server@nvidia.com:${WORKSPACE}/admin-server@nvidia.com
      - ../../../df_stats/jobs/df_stats:/workspace/jobs
      - nvflare_svc_persist:/tmp/nvflare/
  site-1:
    command:
      - ${PYTHON_EXECUTABLE}
      - -u
      - -m
      - nvflare.private.fed.app.client.client_train
      - -m
      - ${WORKSPACE}
      - -s
      - fed_client.json
      - --set
      - secure_train=true
      - uid=site-1
      - org=nvidia
      - config_folder=config
    container_name: site-1
    image: ${IMAGE_NAME}
    volumes:
      - ./site-1:${WORKSPACE}
      - ./admin-site-1@nvidia.com:${WORKSPACE}/admin-site-1@nvidia.com
      - ./data1.csv:/tmp/nvflare/df_stats/data/site-1/data.csv
  site-2:
    command:
      - ${PYTHON_EXECUTABLE}
      - -u
      - -m
      - nvflare.private.fed.app.client.client_train
      - -m
      - ${WORKSPACE}
      - -s
      - fed_client.json
      - --set
      - secure_train=true
      - uid=site-2
      - org=nvidia
      - config_folder=config
    container_name: site-2
    image: ${IMAGE_NAME}
    volumes:
      - ./site-2:${WORKSPACE}
      - ./admin-site-2@nvidia.com:${WORKSPACE}/admin-site-2@nvidia.com
      - ./data2.csv:/tmp/nvflare/df_stats/data/site-2/data.csv
volumes:
  nvflare_svc_persist: null
