services:
  203.101.225.47:
    command:
    - ${PYTHON_EXECUTABLE}
    - -u
    - -m
    - nvflare.private.fed.app.server.server_train
    - -m
    - ${WORKSPACE}
    - -s
    - fed_server.json
    - --set
    - secure_train=true
    - config_folder=config
    - org=nvidia
    container_name: 203.101.225.47
    image: ${IMAGE_NAME}
    ports:
    - 8002:8002
    - 8003:8003
    volumes:
    - ./203.101.225.47:${WORKSPACE}
    - nvflare_svc_persist:/tmp/nvflare/
  site-1:
    command:
    - ${PYTHON_EXECUTABLE}
    - -u
    - -m
    - nvflare.private.fed.app.client.client_train
    - -m
    - ${WORKSPACE}
    - -s
    - fed_client.json
    - --set
    - secure_train=true
    - uid=site-1
    - org=nvidia
    - config_folder=config
    container_name: site-1
    image: ${IMAGE_NAME}
    volumes:
    - ./site-1:${WORKSPACE}
  site-2:
    command:
    - ${PYTHON_EXECUTABLE}
    - -u
    - -m
    - nvflare.private.fed.app.client.client_train
    - -m
    - ${WORKSPACE}
    - -s
    - fed_client.json
    - --set
    - secure_train=true
    - uid=site-2
    - org=nvidia
    - config_folder=config
    container_name: site-2
    image: ${IMAGE_NAME}
    volumes:
    - ./site-2:${WORKSPACE}
volumes:
  nvflare_svc_persist: null
